dataLabels = {
  "Municípios": {
    "nm_mun": "Nome do Município",
    "area_km2": "Área em Km²",
  },
  "Território de Desenvolvimento": {
    "pi_micro_m": "Nome do Território de Desenvolvimento",
    "pi_micro_1": "Região do Estado",
    "pi_micro_2": "Sub-Região",
    "pib_1000": "PIB",
    "parti_esta": "Participação no PIB do estado",
    "obras_e_investimentos": "Obras e Investimentos",
    "qtd_municipios": "Quantidade de municípios",
  },
  "Mesorregiões": {
    "nm_meso": "Nome da Mesorregião",
    "area_km2": "Área (Km²)",
  },
  "Microrregiões": {
    "nm_micro": "Nome da Microrregião",
    "area_km2": "Área em Km²",
  },
  "Regiões Imediatas": {
    "nm_rgi": "Nome da Região Imediata",
    "area_km2": "Área em Km²",
  },
  "Regiões Intermediárias": {
    "nm_rgint": "Nome da Região Intermediária",
    "area_km2": "Área em Km²",
  },
  "Sedes Municipais": {
    "name": "Nome da Sede Municipal",
    "nome_munic": "Nome do Município",
  },
  "Capital Teresina": {
    "NOME": "Nome",
    "TIPOCAPITA": "Tipo",
  },
  'UFPI': {
    "NOME_IES": "Nome da IES",
    "curso": "Cursos",
    "vagas": "Vagas",
    "cargaHoraria": "Carga Horaria",
  },
  "UESPI": {
    "NOME_IES": "Nome da IES",
    "curso": "Cursos",
    "vagas": "Vagas",
    "cargaHoraria": "Carga Horaria",
  },
  "FUVSF": {
    "NOME_IES": "Nome da IES",
    "curso": "Cursos",
    "vagas": "Vagas",
    "cargaHoraria": "Carga Horaria",
  },
  "UFDPAR": {
    "NOME_IES": "Nome da IES",
    "curso": "Cursos",
    "vagas": "Vagas",
    "cargaHoraria": "Carga Horaria",
  },
  "IFPI": {
    "NOME_IES": "Nome da IES",
    "curso": "Cursos",
    "vagas": "Vagas",
    "cargaHoraria": "Carga Horaria",
  },
  "ISEAF": {
    "NOME_IES": "Nome da IES",
    "curso": "Cursos",
    "vagas": "Vagas",
    "cargaHoraria": "Carga Horaria",
  },
  "Usinas Fotovoltaicas": {
    "name": "Nome",
    "Pot_Outorgada": "Potência Outorgada(kw)",
    "Entrada_em_Operacao": "Entrada em Operação",
    "fase": "Fase",
  },
  "Aerogeradores": {
    "name": "Nome",
    "Pot_Outorgada": "Potência Outorgada(kw)",
    "Entrada_em_Operacao": "Entrada em Operação",
    "fase": "Fase",
  },
  "Usinas Hidrelétricas": {
    "name": "Nome",
    "Potência Outorgada (kW)": "Potência Outorgada(kw)",
  },
  "Pecuária": {
    "Ano": "Ano",
    "TipoRebanho": "Tipo de Rebanho",
    "Efetivo": "Efetivo de rebanho",
  },
  "Lavouras Permanentes": {
    "Ano": "Ano",
    "lav_permanente": "Tipo de Produto",
    "Area_destinada_colheita_Hec": "Área destinada a colheita(Hectares)",
    "qtd_produzida_Toneladas": "Quantidade produzida (toneladas)",
    "Valor_da_produção_Mil_Reais": "Valor da Produção(Mil Reais)",
  },
  "Lavouras Temporarias": {
    "Ano": "Ano",
    "lav_temporária": "Tipo de Produto",
    "Area_destinada_colheita_Hec": "Área destinada a colheita(Hectares)",
    "qtd_produzida_Toneladas": "Quantidade produzida (toneladas)",
    "Valor_da_produção_Mil_Reais": "Valor da Produção(Mil Reais)",
  },
  "Aquicultura": {
    "tipo": "Tipo de produção",
    "producao": "Produção",
    "valor_mil_reais": "Valor em Mil Reais",
  },
  "Produção Animal": {
    "tipo_prod": "Tipo de Produto",
    "metrica": "Métrica",
    "prod_animal": "Produção de Origem Animal (Mil)",
    "valor_prod": "Valor da Produção (Mil Reais)",
  },
  "Silvicultura": {
    "Principal tipo de rebanho": "Principal tipo de rebanho",
  },
  "Produção Origem Animal": {
    "Principal tipo de produto de origem animal": "Principal tipo de produto de origem animal",
  },
  "Produção Extração vegetal": {
    "Total quantidade produzida na extração": "Total quantidade produzida na extração",
    "Principal tipo": "Principal tipo",
  },
  "Aeródromos": {
    "nome_da_pista": "Cidade",
    "tipo_do_aeroporto": "Tipo do Aerodromo",
    "nome_do_aeroporto": "Nome do Aerodromo",
    "largura_da_pista(m)": "Largura da Pista(m)",
    "numero_de_pistas": "Número de Pistas",
    "altitude": "Altitude",
    "extensao": "Extensão",
    "cod_uso": "Código de uso",
    "pavimento": "Pavimento",
  },
  "Aeroportos": {
    "tipo_do_aeroporto": "Tipo do Aeroporto",
    "nome_do_aeroporto": "Nome do Aeroporto",
    "largura_da_pista(m)": "Largura da Pista (m)",
    "numero_de_pistas": "Número de Pistas",
    "altitude": "Altitude",
    "extensao": "Extensão",
    "cod_uso": "Código de uso",
    "pavimento": "Pavimento",
  },
  "Ferrovias": {
    "tip_situac": "Situação",
    "bitola": "Bitola",
    "sigla": "Sigla",
    "municipio": "Nome do Municipio",
    "nome_ferrovia": "Nome da Ferrovia",
    "extensao": "Extensão",
    "st_length_": "Comprimento",
    "sigla_coin": "Sigla Coin",
  },
  "Hidrovias": {
    "nome": "Nome",
    "tipo": "Tipo de Hidrovia",
    "extensao": "Extensão",
    "cla_icacao": "Classificação",
    "nome_rio": "Nome do Rio",
    "jurisdicao": "Jurisdicão",
    "reg_rafica": "Região Geográfica",
    "mun_origem": "Município de Origem",
    "est_origem": "Estado de Origem",
    "mun_estino": "Município Destino",
    "est_estino": "Estado Destino",
    "estudos": "Estudos",
    "st_length_": "Comprimento",
  },
  "Rodovias Federais": {
    "objectid": "objectid",
    "id_trecho_": "id_trecho_",
    "vl_br": "Número da BR",
    "nm_tipo_tr": "Nome do Tipo de Trecho",
    "vl_codigo": "Código",
    "ds_local_i": "Descrição do Local Inicial",
    "ds_local_f": "Descrição do Local Final",
    "vl_km_inic": "Quilômetro Inicial",
    "vl_km_fina": "Quilômetro Final",
    "vl_extensa": "Extensão em Quilômetros",
    "ds_sup_fed": "Descrição da Superfície Federal",
    "ds_obra": "Descrição da Obra",
    "ul": "UL",
    "ds_coinc": "Descrição da Coincidência",
    "ds_tipo_ad": "Descrição do Tipo de Administração",
    "ds_ato_leg": "Descrição do Ato Legal",
    "ds_jurisdi": "Descrição da Jurisdição",
    "ds_superfi": "Descrição da Superfície,Descrição da Superfície",
    "ds_legenda": "Descrição da Legenda,Descrição da Legenda",
    "sg_legenda": "Sigla da Legenda,Sigla da Legenda",
    "leg_multim": "Legenda Multimídia,Legenda Multimídia",
    "versao_snv": "Versão SNV",
    "shape_leng": "Comprimento da Forma,Comprimento da Forma",
  },
  "Rodovias Estaduais": {
    "codigo_rod": "Código da Rodovia",
    "superficie": "Extensão",
    "jurisdicao": "Jurisdição",
    "referencia": "Referência",
  },
  "Empresas do Setor Ativas": {
    "Quantidade de empresas": "Quantidade de empresas",
    "Principal atividade": "Principal atividade",
    "Principal porte": "Principal porte",
  },
  "Exportação de Mineração": {
    "Principal país de exportação": "Principal país de exportação",
    "Principal produto": "Principal produto",
    "Valor FOB (US$) em media": "Valor FOB (US$) em media",
    "Quilograma líquido em média": "Quilograma líquido em média",
  },
  "Produção Mineral": {
    "Quantidade de empresas": "Quantidade de empresas",
    "Principal produto": "Principal produto",
    "Quantidade explorada": "Quantidade explorada",
    "Quantidade de área": "Quantidade de área",
  },
  "Empresas PI": {
    "Quantidade de empresas": "Quantidade de empresas",
    "Principal atividade": "Principal atividade",
    "Principal seguimento": "Principal seguimento",
  },
  "Total de Empresas Registradas": {},
  "Empresas por Porte (RFB) Empresarial": {},
  "Empresas por Setor Empresarial ": {},
  "Empregos Diretos Gerados": {},
  "Startups": {
    "Nome da Startup": "Nome da Startup",
    "CNPJ": "CNPJ",
    "Ciclo": "Ciclo",
    "Segmento": "Segmento",
    "Status do Ciclo": "Status do Ciclo",
    "Ano de inicio das atividades": "Ano de inicio das atividades",
    "Maturidade": "Maturidade",
  },
  "HUBs": {
    "Nome do HUB": "Nome do HUB",
  },
}