FROM apache/superset:3.1.0

USER root

RUN pip install mysqlclient
RUN pip install psycopg2
RUN pip install apache-superset[cors]

ENV ADMIN_USERNAME $ADMIN_USERNAME
ENV ADMIN_EMAIL $ADMIN_EMAIL
ENV ADMIN_PASSWORD $ADMIN_PASSWORD

COPY ./superset-init.sh /superset-init.sh

COPY superset_config.py /app/
ENV SUPERSET_CONFIG_PATH /app/superset_config.py
ENV SUPERSET_LOAD_EXAMPLES $SUPERSET_LOAD_EXAMPLES

USER superset
ENTRYPOINT [ "/superset-init.sh" ]