FROM python:3.11-slim

WORKDIR /app

EXPOSE 3000

# INSTALL PSYCOPG2 DEPENDENCIES
RUN apt-get update && apt-get install -y libpq-dev gcc

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
